(dp1
S'output'
p2
S"<type 'exceptions.SyntaxError'> Object exists and cannot be redefined: testbool"
p3
sS'layer'
p4
S'/home/topf/Web2Py/web2py/applications/Asylum/controllers/asylum.py'
p5
sS'code'
p6
S'<code object <module> at 0xae6084a0, file "/home/topf/Web2Py/web2py/applications/Asylum/controllers/asylum.py", line 3>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/topf/Web2Py/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/topf/Web2Py/web2py/applications/Asylum/controllers/asylum.py", line 152, in <module>\n  File "/home/topf/Web2Py/web2py/gluon/globals.py", line 409, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/topf/Web2Py/web2py/gluon/tools.py", line 3964, in f\n    return action(*a, **b)\n  File "/home/topf/Web2Py/web2py/applications/Asylum/controllers/asylum.py", line 103, in grid1_pbase\n    db.asylum_pbase.bankiban.show_if = db.asylum_pbase.testbool = True\n  File "/home/topf/Web2Py/web2py/gluon/packages/dal/pydal/objects.py", line 607, in __setattr__\n    \'Object exists and cannot be redefined: %s\' % key)\nSyntaxError: Object exists and cannot be redefined: testbool\n'
p11
s.