(dp1
S'output'
p2
S"<type 'exceptions.TypeError'> process() takes exactly 1 argument (3 given)"
p3
sS'layer'
p4
S'/home/topf/Web2Py/web2py/applications/Asylum/controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 0xaf4fc6e0, file "/home/topf/Web2Py/web2py/applications/Asylum/controllers/default.py", line 12>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/topf/Web2Py/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/topf/Web2Py/web2py/applications/Asylum/controllers/default.py", line 138, in <module>\n  File "/home/topf/Web2Py/web2py/gluon/globals.py", line 409, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/topf/Web2Py/web2py/applications/Asylum/controllers/default.py", line 50, in widget_examples\n    if form.process(request,session).accepted:\nTypeError: process() takes exactly 1 argument (3 given)\n'
p11
s.