(dp1
S'output'
p2
S"<type 'exceptions.TypeError'> 'str' object is not callable"
p3
sS'layer'
p4
S'/home/topf/Web2Py/web2py/applications/Asylum/controllers/asylum.py'
p5
sS'code'
p6
S'<code object <module> at 0xaf378770, file "/home/topf/Web2Py/web2py/applications/Asylum/controllers/asylum.py", line 3>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/topf/Web2Py/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/topf/Web2Py/web2py/applications/Asylum/controllers/asylum.py", line 144, in <module>\n  File "/home/topf/Web2Py/web2py/gluon/globals.py", line 409, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/topf/Web2Py/web2py/gluon/tools.py", line 3964, in f\n    return action(*a, **b)\n  File "/home/topf/Web2Py/web2py/applications/Asylum/controllers/asylum.py", line 113, in grid1_pbase\n    links = dict(header=\'name\',body=lambda row: A(\'link text\', _href=URL(index))),\n  File "/home/topf/Web2Py/web2py/gluon/sqlhtml.py", line 2920, in grid\n    if link(row):\nTypeError: \'str\' object is not callable\n'
p11
s.