(dp1
S'output'
p2
S"<class 'sqlite3.IntegrityError'> FOREIGN KEY constraint failed"
p3
sS'layer'
p4
S'/home/topf/Web2Py/web2py/applications/Asylum/controllers/asylum.py'
p5
sS'code'
p6
S'<code object <module> at 0xaebf8ba8, file "/home/topf/Web2Py/web2py/applications/Asylum/controllers/asylum.py", line 4>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/topf/Web2Py/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/topf/Web2Py/web2py/applications/Asylum/controllers/asylum.py", line 331, in <module>\n  File "/home/topf/Web2Py/web2py/gluon/globals.py", line 409, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/topf/Web2Py/web2py/gluon/tools.py", line 3964, in f\n    return action(*a, **b)\n  File "/home/topf/Web2Py/web2py/applications/Asylum/controllers/asylum.py", line 69, in manage\n    grid = SQLFORM.grid(db[table], args=request.args[:1], links_in_grid=True,\n  File "/home/topf/Web2Py/web2py/gluon/sqlhtml.py", line 2421, in grid\n    onsuccess=oncreate)\n  File "/home/topf/Web2Py/web2py/gluon/html.py", line 2300, in process\n    self.validate(**kwargs)\n  File "/home/topf/Web2Py/web2py/gluon/html.py", line 2238, in validate\n    if self.accepts(**kwargs):\n  File "/home/topf/Web2Py/web2py/gluon/sqlhtml.py", line 1857, in accepts\n    self.vars.id = self.table.insert(**fields)\n  File "/home/topf/Web2Py/web2py/gluon/packages/dal/pydal/objects.py", line 734, in insert\n    ret = self._db._adapter.insert(self, row.op_values())\n  File "/home/topf/Web2Py/web2py/gluon/packages/dal/pydal/adapters/base.py", line 484, in insert\n    raise e\nIntegrityError: FOREIGN KEY constraint failed\n'
p11
s.